### PR TITLE
Keep rendering components after error in prod

### LINKED ISSUE #36: Ember.assert not available in production
In our project, we're using Ember with ember-islands to partially show content on a pre-rendered page. The island divs are delivered by the pre-render engine as well. We had the issue, that the `data-component` attribute sometimes contained an invalid or not yet implemented component name. This caused the following method to crash (on `component.create(attrs)`):

```
// ember-islands.js
function getRenderComponentFor(emberObject) {
  let owner = getOwner(emberObject);

  return function renderComponent({ name, attrs, element }) {
    let { component, layout } = lookupComponent(owner, name);
    assert(`ember-islands could not find a component named "${name}" in your Ember appliction.`, component);

    if (layout) {
      attrs.layout = layout;
    }

    $(element).empty();
    let componentInstance = component.create(attrs);
    componentInstance.appendTo(element);
    return componentInstance;
  };
}
```

I think this is caused, because according to the Ember API assert is only available in non-production builds (http://emberjs.com/api/#method_assert). I think in this case it would be better, to also add an error handler, which would prevent code execution and give a console feedback, if the given component was not found.

### PR DESCRIPTION
**Pull request by mitchlloyd**
In production mode, don't stop rendering components after finding that
one is missing. Instead render a no-op (but overridable component) and
log an error. 

[fix #36]

@patric-eberle could you try this branch out?

I think this can be a minor release but I'm not sure. There is a chance that someone could be using the error message from Ember Islands in production mode by extending the ember-islands component and overriding the `didInsertElement` hook.

### CODE REVIEW

**Comment by patric-eberle** [comment]
@mitchlloyd I will try to test your solution somewhen this week.

File: addon/components/ember-islands.js [hunk 1]
```diff
@@ -79,3 +84,13 @@ function lookupComponent(owner, name) {
 
   return { component, layout };
 }
+
+function missingComponentMessage(name) {
+  return `ember-islands could not find a component named "${name}" in your Ember appliction.`;
```
Comment (patric-eberle) [inline addon/components/ember-islands.js]: There is a typo in "appliction". Should be "application".

**Comment by mitchlloyd** [comment]
Thanks for reviewing! Released as version 1.2.0.
